# Generated by Django 3.2.9 on 2021-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_response', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Response Status Log',
                'verbose_name_plural': 'Response Status Logs',
            },
        ),
    ]
